### PR TITLE
Fixed Line Height 

### LINKED ISSUE #15491: Bug report: floating feedback widget styling
### Describe the bug

At the right bottom of each page we have a floating feedback widget

default state
Image

Expanded state after certain criteria are met.

Image

- the styling in some languages is broken

- [ ] lower the line-height of the text to feel natural - 1.2 rem

### To reproduce

1. go to https://ethereum.org/de/
2. scroll to the bottom of the page
3. wait 30 secs
4. the widget expands automatically

### Expected behavior

Image

1.2 rem line height

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by YashIIT0909**
## Description

Added the CSS, for the appropriate line height of the feedback widget.

## Related Issue

- Fixes #15491

### CODE REVIEW

**Review by konopkja — APPROVED** [review]

File: src/components/FeedbackWidget/FixedDot.tsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ const FixedDot = forwardRef<HTMLButtonElement, FixedDotProps>(
         >
           <span
             className={cn(
-              "line-clamp-2 hidden h-full items-center font-bold text-white",
+              "line-clamp-2 hidden h-full items-center font-bold text-white leading-[1.2rem]",
```
Comment (wackerow) [inline src/components/FeedbackWidget/FixedDot.tsx]: image

@konopkja `1.2rem` is a non-standard value, any change we could adjust ever-so-slightly to just use the `5` token? (`1.25rem`)

```suggestion
              "line-clamp-2 hidden h-full items-center font-bold text-white leading-5",
```

image

**Comment by wackerow** [comment]
@all-contributors please add @YashIIT0909 for bug fix
