### PR TITLE
fix: fixed date format

### LINKED ISSUE #11335: Incorrect intl number formatting
### Describe the bug

Dates on event cards are not being formatted using intl locale.

### To reproduce

1. Go to https://ethereum.org/zh/community/events/
2. Notice date format in event cards compared to date at the top of the page.

### Expected behavior

Despite the contents of these cards not being translated into other languages, I would expect these dates to be rendered according to the locale.

The [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) should be used by passing the current locale and the date to render accordingly.

### Screenshots

image

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by ameeetgaikwad**
## Description
Created a function in src/lib/utils/date.ts which can be used to format dates in a certain format according to the language.

## Related Issue
fixes #11335
closes #11443

### CODE REVIEW

**Comment by nhsz** [comment]
@wackerow I think PR https://github.com/ethereum/ethereum-org-website/pull/12209 overlaps a bit with this one, not sure if this one is still needed

File: src/lib/utils/date.ts [hunk 1]
```diff
@@ -1,2 +1,5 @@
 export const dateToString = (published: Date | string) =>
   new Date(published).toISOString().split("T")[0]
+export const formatDate = (date: Date, locale: string): string => {
+  return Intl.DateTimeFormat(locale).format(date)
+}
```
Comment (wackerow) [inline src/lib/utils/date.ts:5]: We have `getLocaleTimestamp` inside `src/lib/utils/time.ts` which does this same thing with a bit more flexibility and type safety (allowing display options to be passed for example).

I think we should remove this addition and use `getLocaleTimestamp` instead

File: src/components/UpcomingEventsList.tsx [hunk 2]
```diff
@@ -56,10 +59,11 @@ const UpcomingEventsList = () => {
...
         event.startDate === event.endDate
-          ? dateParse(event.startDate).toLocaleDateString()
-          : `${dateParse(event.startDate).toLocaleDateString()} - ${dateParse(
-              event.endDate
-            ).toLocaleDateString()}`
+          ? formatDate(dateParse(event.startDate), locale)
+          : `${formatDate(dateParse(event.startDate), locale)} - ${formatDate(
+              dateParse(event.endDate),
+              locale
+            )}`
```
Comment (wackerow) [inline src/components/UpcomingEventsList.tsx:66]: Would update this to use `getLocaleTimestamp` from `time.ts`... it accepts the `locale`, (of `Lang` type) then `timestamp` as a string (then optional `options` override argument which may be able to be left out here)

ie. `getLocaleTimestamp(locale! as Lang, dateParse(event.startDate).getTime())`

`locale!` force unwraps it, since we know we'll get a locale back from `useRouter`... and `as Lang` casts it to the expected type as defined inside `getLocaleTimestamp`.

^ With this, we need to fix the `locale` instantiation (see above), and also import `Lang` type above:

`import type { CommunityConference, Lang } from "@/lib/types"`

File: src/components/UpcomingEventsList.tsx [hunk 3]
```diff
@@ -19,6 +21,7 @@ type OrderedUpcomingEvent = CommunityConference & {
 }
 
 const UpcomingEventsList = () => {
+  const { locale = "" } = useRouter()
```
Comment (wackerow) [inline src/components/UpcomingEventsList.tsx:24]:
```suggestion
  const { locale } = useRouter()
```

File: src/components/UpcomingEventsList.tsx [hunk 4]
```diff
@@ -9,6 +10,7 @@ import EventCard from "@/components/EventCard"
 import InfoBanner from "@/components/InfoBanner"
 import InlineLink from "@/components/Link"
 
+import { formatDate } from "@/lib/utils/date"
```
Comment (wackerow) [inline src/components/UpcomingEventsList.tsx:13]:
```suggestion
```

File: src/lib/utils/date.ts (hunk 1 above)
Comment (wackerow) [reply src/lib/utils/date.ts:5]:
```suggestion
```

**Review by wackerow — CHANGES_REQUESTED** [review]
Hey @ameeetgaikwad! Thanks for the PR... as @nhsz mentioned, we do have some other related helper functions already in the codebase for this.. Left some suggestions as to how we could reuse these and get this cleaned up. Let us know if you hit issues!

**Comment by wackerow** [comment]
Just pushed a commit to update this with the latest from `dev` branch

**Comment by nhsz** [comment]
@wackerow do you think this PR is still relevant?

**Review by wackerow — APPROVED** [review]
Went ahead and made a few updates to just use the getLocaleTimestamp function that already exists. Made a little helper function in-component to avoid repeating the options we want for this specific component. Pulling in!

**Comment by wackerow** [comment]
> @wackerow do you think this PR is still relevant?

@nhsz And yes, this patches the number formatting on the community events page
