### PR TITLE
Fixes isGlossary console warnings [Fixes #2259]

### LINKED ISSUE #2259: React does not recognize the `isGlossary` prop on a DOM element
**Describe the bug**

The Link prop `isGlossary` we're passing to conditionally style the component is causing issues:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Link.js#L151

**Expected behavior**

Fix the console error! Let's sort out a way to customize this styling. Might be an issue with adding custom props to `IntlLink` from "gatsby-plugin-intl".

One approach: add a `className` to the link & style the class in the parent styled component.

**Additional context**

Created in #2130

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Switched `isGlossary` prop to a className
- Selected for `.isGlossary` className in CSS, and applied `whitespace: nowrap;` styling

Now rendering appropriately without DOM warnings

### CODE REVIEW

File: src/components/Link.js [hunk 1]
```diff
@@ -144,11 +146,10 @@ const Link = ({
   // Use `gatsby-plugin-intl` Link (which prepends lang path)
   return (
     <InternalLink
-      className={className}
+      className={isGlossary ? `isGlossary ${className}` : className}
```
Comment (samajammin) [inline src/components/Link.js:149]:
```suggestion
      className={isGlossary ? `is-glossary ${className}` : className}
```

File: src/components/Link.js [hunk 2]
```diff
@@ -31,7 +31,9 @@ const ExternalLink = styled.a`
 `
 
 const InternalLink = styled(IntlLink)`
-  white-space: ${(props) => (props.isGlossary ? `nowrap` : `normal`)};
+  .isGlossary {
```
Comment (samajammin) [inline src/components/Link.js:34]:
```suggestion
  .is-glossary {
```

**Review by samajammin — APPROVED** [review]
