### PR TITLE
fix: Implement DS styles and unify modals

### LINKED ISSUE #10749: Modal - implement DS styles and unify modals
The goal is to implement the DS styles for the modal and unify all the instances where we use modals.

TODO:
1. Implement latest styles from [the DS](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=1630%3A32303) to the Modal [theme](https://github.com/ethereum/ethereum-org-website/blob/dev/src/%40chakra-ui/gatsby-plugin/components/Modal.ts) and [component](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Modal.tsx).

2. Remove the all the other existing modal implementations and start using this one for everything.

Other modal implementations we currently have:
- [CodeModal](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/CodeModal.tsx)
- [QuizzesModal](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Quiz/QuizzesModal.tsx)

### PR DESCRIPTION
**Pull request by ashiskumar-1999**
## Description
Implemented the styles from the DS to the Modal theme file & component. Replaced the existing modal implementation with the current Modal.

- Added the DS styles from Figma in the theme file(@chakra-ui/gatsby-plugin/components/Modal.ts) & removed styles from the ModalContent in the Component file(components/Modal.tsx).
- Replaced the current QuizessModal implementation with the current Modal Component.
- Implemented the current Modal component in the `index.tsx` file instead of CodeModal component.

## Preview link
- https://deploy-preview-11212--ethereumorg.netlify.app/

## Related Issue
- Closes #10749

### CODE REVIEW

**Comment by TylerAPfledderer** [comment]
Taking a quick moment to mention that `Closes #10749` should be added to the description so this PR is automatically tied to that issue.

**Comment by ashiskumar-1999** [comment]
Thanks @TylerAPfledderer
Added it.

**Comment by TylerAPfledderer** [comment]
@ashiskumar-1999 hmmm, I believe there are two things that should be done first before this can get a proper review:
1. All the styling under `variantCode` in the component theming is related to the `CodeModal` component that can be seen of the home page. Head to the [Site preview deploy of this PR](https://ethereumorgwebsitedev01-ashiskumar1999ethereumorgwebsi.gatsbyjs.io/), scroll down to the section called "A new frontier for development" and select one of the options in that list to see the modal.

Screen Shot 2023-09-30 at 23 21 39

Since the `CodeModal` is likely to be using this same general styling, I would take all of the styling from `variantCode` and move it to `baseStyle` and address the compressed width of `CodeModal` from there. (I'd recommend simply removing the `maxWidth` from the `dialog` part for now and use `size="2xl"` instead)

This would mean `Modal` should have no `variant`, and `CodeModal` is basically redundant against the custom `Modal` that has been added.

2. All components related to the Design System need to be added to Storybook with a stories file. So `Modal.tsx` needs to be converted to `Modal/index.tsx` and add the stories file in this new folder as `Modal.stories.tsx`.  For the directory title the new story is housed in, it should be `Molecules / Overlay Content / Modal`.

For further guidance on creating this stories file and using it for visual testing, there is a doc in the project repo to view. However, I just recognized that it is a bit out-of-date. Therefore, I would view the file via a PR I just opened. [See this commit of the file from that PR](https://github.com/ethereum/ethereum-org-website/blob/862e7ceed5e6bc1e914cbfb230271437b1e3200f/docs/applying-storybook.md) and we'll go from there.

**Comment by ashiskumar-1999** [comment]
Hi @TylerAPfledderer, 
Addressed the above comments. Review this once in your available time.

File: src/@chakra-ui/gatsby-plugin/components/Modal.ts [hunk 1]
```diff
@@ -11,57 +11,68 @@ const {
...
+ 
+})) */
 
 export const Modal = defineMultiStyleConfig({
   baseStyle: definePartsStyle((props) =>
     defineMergeStyles(defaultBaseStyle?.(props), {
+      overlay: {
+        bg: "rgba(0, 0, 0, 0.7)",
+      },
       dialog: {
```
Comment (TylerAPfledderer) [inline src/@chakra-ui/gatsby-plugin/components/Modal.ts:26]: Add `gap: "4"` for the dialog to establish the primary spacing between the content.

File: src/pages/quizzes.tsx [hunk 2]
```diff
@@ -95,14 +96,14 @@ const QuizzesHubPage = ({ data }: PageProps<Queries.QuizzesHubPageQuery>) => {
       </Box>
 
       <QuizzesHubContext.Provider value={contextState}>
-        <QuizzesModal isOpen={isOpen} onClose={onClose}>
+        <Modal isOpen={isOpen} setIsOpen={onClose}>
```
[the remark this answers is not in the document]
Comment (ashiskumar-1999) [reply src/pages/quizzes.tsx:99]: I think we should use directly the Modal component instead of updating the QuizzesModal. Because we have set another prop for the isOpen & setIsOpen prop of the custom Modal & we can add the value where the QuizzesModal component is being rendered. What do you think?

File: src/@chakra-ui/gatsby-plugin/components/Modal.ts [hunk 3]
```diff
@@ -11,57 +11,67 @@ const {
...
-        my: 0,
+        size: "2xl",
+        /* maxW: "464px", */
+        my: "64px",
+        mx: "8px",
+        gap: 4,
+        padding: "32px",
+        maxHeight: "70%",
+        borderRadius: "4px",
+      },
```
Comment (TylerAPfledderer) [inline src/@chakra-ui/gatsby-plugin/components/Modal.ts:35]:
```suggestion
        bg: "background.base",
        gap: "4",
        padding: "8",
        maxW: "464px",
        borderRadius: "md",
        boxShadow: "none",
      },
```
A couple of points here:
1. There should only be style props used in the theme objects, and `size` is not a style prop. The `maxW` prop should be used here because the default sizes to choose from use default size tokens and `464px` does not match any of the tokens. (@nloureiro for your awareness. The DS example has a width value that is not equal to any of the current token values to choose from. Need to consider a value of `448px` or `512px` if we are to use an existing token.)
2. Need to make sure we have the default `boxShadow` removed.
3. `borderRadius` needs to use the matching token value.
4. `maxHeight` does not need to be defined here, Unless @nloureiro has a particular height constraint in mind to force scrolling of the content.
5. The background color needs to be defined with a semantic token to ensure it matches with the DS (the default values do not match the DS)
6. Margin values do nothing here because the modal is absolutely positioned.

File: src/@chakra-ui/gatsby-plugin/components/Modal.ts [hunk 4]
```diff
@@ -11,57 +11,67 @@ const {
...
+          props.colorMode === "dark" ? "rgb(25, 25, 25)" : "rgb(247, 247, 247)", */
+        borderColor:
+          props.colorMode == "dark" ? "rgb(242, 242, 242)" : "rgb(51, 51, 51)",
+        /* borderTop: "1px solid",
+        borderBottom: "1px solid", */
+        padding: 0,
+        fontWeight: "bold",
+        fontSize: "2xl",
+        fontFamily: "Inter",
+      },
```
Comment (TylerAPfledderer) [inline src/@chakra-ui/gatsby-plugin/components/Modal.ts:47]:
```suggestion
      header: {
        padding: 0,
        fontWeight: "bold",
        fontSize: "2xl",
      },
```
Excessive styling here.

File: src/@chakra-ui/gatsby-plugin/components/Modal.ts [hunk 5]
```diff
@@ -11,57 +11,67 @@ const {
...
+        borderRadius: 0,
+        color: "rgb(178, 178, 178)",
+        fontSize: "sm",
+        marginTop: 5,
+      },
+      body: {
+        padding: 0,
+        fontWeight: "normal",
+        fontSize: "md",
+        fontFamily: "Inter",
```
Comment (TylerAPfledderer) [inline src/@chakra-ui/gatsby-plugin/components/Modal.ts:61]:
```suggestion
```
Redundant styling

File: src/@chakra-ui/gatsby-plugin/components/Modal.ts [hunk 6]
```diff
@@ -11,57 +11,67 @@ const {
...
+      },
+      footer: {
+        gap: "8px",
```
Comment (TylerAPfledderer) [inline src/@chakra-ui/gatsby-plugin/components/Modal.ts:64]:
```suggestion
        gap: "2",
```

File: src/@chakra-ui/gatsby-plugin/components/Modal.ts [hunk 7]
```diff
@@ -11,57 +11,67 @@ const {
...
   ),
   sizes: defaultSizes,
-  variants: {
+  /* variants: {
     code: variantCode,
-  },
+  }, */
   defaultProps: {
     ...defaultProps,
     variant: undefined,
```
Comment (TylerAPfledderer) [inline src/@chakra-ui/gatsby-plugin/components/Modal.ts:77]: I think all of this should be removed. Per the DS, it is suggested that we will only be using one size and style of modal.

However, a couple of the `size` are being used in the `QuizzesModal` component. So do not remove for now!

---
For @pettinarip  below:

I stated in another comment about having to hard-code the `maxWidth` value of the dialog part because the value used in the DS does not have a corresponding size token that is available.

The `QuizzesModal` component is using a size value that is larger than in the DS.

And if we keep the `sizes` object from the default theme as well as the default `size` being used, it will override the hard-coded `maxW` value in the dialog part.

Does this make sense?

File: src/@chakra-ui/gatsby-plugin/components/Modal.ts [hunk 8]
```diff
@@ -11,57 +11,67 @@ const {
...
-  },
-  body: {
-    padding: 0,
-  },
-}))
+// Remove all the comment line once the review is completed & PR will able to merge
+
+/* const variantCode = definePartsStyle((props) => ({
+ 
+})) */
```
Comment (TylerAPfledderer) [inline src/@chakra-ui/gatsby-plugin/components/Modal.ts:18]:
```suggestion
```

File: src/pages/index.tsx [hunk 9]
```diff
@@ -94,7 +95,7 @@ const StyledActionCard = chakra(ActionCard, {
   },
 })
 
-const StyledCodeModal = chakra(CodeModal)
+const StyledCodeModal = chakra(Modal)
```
[the remark this answers is not in the document]
Comment (TylerAPfledderer) [reply src/pages/index.tsx:95]: @ashiskumar-1999 don't forget to remove the `CodeModal` import, since it no longer exists.

File: src/components/Modal/Modal.stories.tsx [hunk 10]
```diff
@@ -0,0 +1,18 @@
...
+export default meta
+type Story = StoryObj<typeof meta>
+export const Modal: Story = {
+  args: {
+    isOpen: true,
+    title: "Modal Title",
+    children:
+      "This is the base component to be used in the modal window.Please change the text to preview final content for ethereum.org",
+  },
+}
```
Comment (TylerAPfledderer) [inline src/components/Modal/Modal.stories.tsx:18]: I would update this to render the DS example, which includes header text, body text, and a footer with two `Button` components, so that we have a good representation of the styles being rendered and continue the consistency with what the examples show.

File: src/pages/quizzes.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (TylerAPfledderer) [reply src/pages/quizzes.tsx:95]: @ashiskumar-1999 it's more about the custom styling that is added to this instance of the modal and keeping that styling in isolation. In particular, there is conditional rendering of the background color and the use of the size prop based on screen size.

Also it would be easier to continue handling the background style in `QuizzesModal` than trying to do the logic in a variant for something primitive. That's not how a theme variant should be applied.

**Review by TylerAPfledderer — CHANGES_REQUESTED** [review]
Hey @ashiskumar-1999! Thank you for your efforts on this. 

My apologies; I have an exhaustive list of thoughts here. 😅  I didn't get through everything I noticed, but I think these are the primary points to address before more refinement can be made.

So we are on the same page, please make sure you are comparing your changes to what is shown in the [DS figma file](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=1631%3A32065&mode=design&t=kfjObDVwtgDJlI7h-1). It looked like to me that there were changes that were not quite lining up with the design we are trying to implement.

**Comment by ashiskumar-1999** [comment]
Hi @TylerAPfledderer, 
updated with the `dev` branch & committed the necessary changes. Ran the `yarn lint: fix`. Please check with your available time. Also, try to merge this PR ASAP before any commits happen to the `dev` branch because the conflict that we're getting i.e `CodeModal.tsx` no longer exist in my local changes since it is of no usage but it still exists in the `dev` branch. That's why I think the conflict is happening.

**Comment by Coretaker101** [comment]
?

**Comment by TylerAPfledderer** [comment]
> Hi @TylerAPfledderer, 
> updated with the `dev` branch & committed the necessary changes. Ran the `yarn lint: fix`. Please check with your available time. Also, try to merge this PR ASAP before any commits happen to the `dev` branch because the conflict that we're getting i.e `CodeModal.tsx` no longer exist in my local changes since it is of no usage but it still exists in the `dev` branch. That's why I think the conflict is happening.

It's normal for conflicts to occur when a PR is no longer up-to-date with the main branch. Now that this one is up-to-date, you should not see the same conflicts again, even if other PRs get pushed.

Conflicts are only related to changes you made in this PR. Because one change involves removing an entire file, if someone merges a PR where they only make a change within said file, you should not receive a new conflict. Otherwise, it's easy to fix and it's just a part of the PR process 😁

**Comment by ashiskumar-1999** [comment]
Got it @TylerAPfledderer . So, Now we can merge this PR since it is up to date with the `dev` branch. Can you merge this PR?

**Comment by TylerAPfledderer** [comment]
I'm not a team member. @pettinarip or one of the other members needs to provide the final review before merging.

**Comment by ashiskumar-1999** [comment]
Ohh. Thanks for letting me know @TylerAPfledderer .

File: src/@chakra-ui/components/Modal.ts [hunk 11]
```diff
@@ -12,57 +12,46 @@ const {
...
+      overlay: {
+        bg: "gray.500",
+      },
       dialog: {
-        my: 0,
+        bg: "background.base",
+        gap: "4",
+        padding: "8",
+        maxW: "464px",
+        borderRadius: "md",
```
Comment (wackerow) [inline src/@chakra-ui/components/Modal.ts:26]: https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=1630-32303&mode=design

Looks like we're using a 4px border radius, which would be the `base` token:

```suggestion
        borderRadius: "base",
```

File: src/components/Modal/index.tsx [hunk 12]
```diff
@@ -40,8 +47,15 @@ const Modal = ({
         borderRadius="md"
```
Comment (wackerow) [inline src/components/Modal/index.tsx:47]: In line with other comment, I think we can remove this and just use the `base` token declared in the theme file

```suggestion
```

File: src/components/Modal/index.tsx [hunk 13]
```diff
@@ -1,33 +1,40 @@
...
-  size,
   ...restProps
 }: ModalProps) => {
   return (
     <ChakraModal
       isOpen={isOpen}
       onClose={() => setIsOpen(false)}
       isCentered
-      size={size ?? "xl"}
+      /* size={size ?? "xl"} */
```
Comment (wackerow) [inline src/components/Modal/index.tsx:37]: ✂️

```suggestion
```

File: src/@chakra-ui/components/Modal.ts [hunk 14]
```diff
@@ -12,57 +12,46 @@ const {
...
+        top: "8",
+        insetInlineEnd: "8",
+      },
+      body: {
+        padding: 0,
+        fontWeight: "normal",
+        fontSize: "md",
+      },
+      footer: {
+        gap: "8px",
```
Comment (wackerow) [inline src/@chakra-ui/components/Modal.ts:46]: (Chakra token `2` = 8px)

```suggestion
        gap: "2",
```

**Review by wackerow — CHANGES_REQUESTED** [review]
Hey @ashiskumar-1999! Apologies for delays here but would love to help get this over the line...

I pushed a couple small commits to just clear the merge conflicts and run the linter. Left a couple tiny requests to get this in a final state, as otherwise this looks good to go from a code standpoint. 

Can help finish this up as well if you're busy, appreciate the work so far.

cc: @nloureiro for design review

cc: @TylerAPfledderer if you have any last thoughts, thanks so much for the feedback so far on this

File: src/@chakra-ui/components/Modal.ts [hunk 15]
```diff
@@ -12,57 +12,46 @@ const {
...
+        px: 0,
+        pt: 8,
```
Comment (wackerow) [inline src/@chakra-ui/components/Modal.ts:48]: For consistency with others
```suggestion
        pt: "8",
```

**Comment by ashiskumar-1999** [comment]
Hi @wackerow, Thanks for the requested changes. I can make all the necessary changes once @nloureiro verifies the designs.

**Comment by nloureiro** [comment]
This needs further testing; maybe @konopkja can help do some Q&A on the models here.

I found one bug on the width of the modal on the quizzes

on the dev preview is like this:
Screen Shot 2024-04-04 09 31 18 AM

in production is like this:
Screen Shot 2024-04-04 09 31 42 AM

**Comment by ashiskumar-1999** [comment]
Hi @nloureiro ,
Not sure but I think this is happening because of the maxW prop that we've in the styles fo the Modal. Also, let me know once you've finished the design review.

**Comment by pettinarip** [comment]
@nloureiro PR ready for review (once the build finishes).

As discussed, we have:
- on mobile, used the same styles used in the Simulator modal
- unified the sizes of the modals
- the close button is not `absolute` positioned, now it is part of the header structure
- the modal padding is 32px

The affected modals and pages where you can see them are:

- default Modal
    - https://deploy-preview-11212--ethereumorg.netlify.app/en/developers/tutorials/
    - https://deploy-preview-11212--ethereumorg.netlify.app/en/developers/docs/
- CodeModal - unique modal that has its own styles
    - https://deploy-preview-11212--ethereumorg.netlify.app/en/
- QuizzesModal
    - https://deploy-preview-11212--ethereumorg.netlify.app/en/quizzes/
- SimulatorModal
    - https://deploy-preview-11212--ethereumorg.netlify.app/en/wallets/

**Comment by nloureiro** [comment]
@pettinarip looks great!  great work

I found one tiny, tiny detail that it's not a blocker. I will create an issue later on.

**Comment by wackerow** [comment]
@pettinarip This look ready from your perspective?

I'm noticing the content of the Quiz modal

Production (left aligned text, full width content):
image

PR (center aligned text, fits-to-content)
image

**Comment by nloureiro** [comment]
> @pettinarip This look ready from your perspective?
> 
> I'm noticing the content of the Quiz modal
> 
> Production (left aligned text, full width content): image
> 
> PR (center aligned text, fits-to-content) image


From my side, it's better centered.
On the original Figma it's centered, too.

Screen Shot 2024-05-25 11 12 43 AM

**Review by wackerow — APPROVED** [review]

**Review by pettinarip — APPROVED** [review]
