### PR TITLE
Fix the unintended behaviour of clicking visit website on find wallet #12644

### LINKED ISSUE #12644: Bug report: find wallet - clicking "Visit website" unintended behavior
### Describe the bug

clicking on main "visit website" button in wallet listings unintentionally also opens wallet detail which triggers additional event and distorts our usage reports.

### To reproduce

1. Go to https://ethereum.org/en/wallets/find-wallet/
2. Click on "visit website" of any wallet
3. wallet detail opens (should not)

### Expected behavior

wallet detail does not open, this is unintended behavior and is namely problematic because it also triggers "More info wallet" event which distorts the data.

In event reports it now looks that clicking on wallet detail is more popular than in reality it is because of this dynamic

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by Dharmik79**
## Description

When the Visit website is clicked on the wallet, the event is compared with the associated class and allows to show the detailed view accordingly. [Fixes #12644 ]

### CODE REVIEW

File: src/components/FindWallet/WalletTable/index.tsx [hunk 1]
```diff
@@ -328,9 +336,11 @@ const WalletTable = ({
               <Wallet
                 // Make wallets more info section open on 'Enter'
                 onKeyUp={(e) => {
-                  if (e.key === "Enter") showMoreInfo(wallet)
+                  if (e.key === "Enter") showMoreInfo(wallet, e)
+                }}
+                onClick={(e) => {
+                  showMoreInfo(wallet, e)
```
Comment (wackerow) [inline src/components/FindWallet/WalletTable/index.tsx:342]: Hey @Dharmik79, thanks for taking a stab at this! I don't think we need to get into looking at class names here... I think this could be solved with a one-liner to just check if the event target is an "A" tag, and if so, return early to avoid toggling "showMoreInfo"

```suggestion
                onClick={(e) => {
                  if ((e.target as HTMLTableRowElement).tagName === "A") return
                  showMoreInfo(wallet)
```

**Review by wackerow — CHANGES_REQUESTED** [review]
Thanks @Dharmik79, left my thoughts!

File: src/components/FindWallet/WalletTable/index.tsx (hunk 1 above)
Comment (Dharmik79) [reply src/components/FindWallet/WalletTable/index.tsx:342]: Hey @wackerow, The solution will work only when the button is pressed, but by clicking the SVG icon within the button unintentionally triggers both the 'showMoreInfo' function and opens a new page simultaneously. To resolve this, I have used 'classList' to specifically address and prevent the issue from occurring when the button or the SVG inside the button is clicked.

Comment (Dharmik79) [reply src/components/FindWallet/WalletTable/index.tsx]: I have added the below code along with your suggestion to avoid the showMoreInfo function call.

 `   (e.target as HTMLTableRowElement).tagName === "A" ||
                    (e.target as HTMLTableRowElement).tagName === "svg"`

**Comment by Dharmik79** [comment]
@wackerow I have added the code according to the suggestion provided.

File: src/components/FindWallet/WalletTable/index.tsx (hunk 1 above)
Comment (Dharmik79) [reply src/components/FindWallet/WalletTable/index.tsx]: @wackerow  I have added the below code to resolve the issue, but if click on the arrow icon for the right side, then it will not open. So, I have used classList to resolve the issue.

`  if (
              Object.values(classList)?.includes("chakra-button") ||
              Object.values(classList)?.includes("css-1bbj57d")
            ) {
              return
            }`
Should I revert the code, with the classList or not?

File: src/components/FindWallet/WalletTable/index.tsx [hunk 2]
```diff
@@ -330,7 +332,14 @@ const WalletTable = ({
                 onKeyUp={(e) => {
                   if (e.key === "Enter") showMoreInfo(wallet)
                 }}
-                onClick={() => showMoreInfo(wallet)}
+                onClick={(e) => {
+                  if (
+                    (e.target as HTMLTableRowElement).tagName === "A" ||
+                    (e.target as HTMLTableRowElement).tagName === "svg"
```
Comment (wackerow) [inline src/components/FindWallet/WalletTable/index.tsx:338]: @Dharmik79 Ahh, good catch with the SVG, but careful because this line will now prevent it from opening for any SVG in this entire box, which there are a few and we don't want that.

I'd suggest we switch to a selector approach, since we only want to get the svg's that are inside an anchor link:

```suggestion
                    (e.target as HTMLElement).matches("a, a svg")
```

**Comment by konopkja** [comment]
Hi @Dharmik79 and @wackerow - what do we need to do here to get this fix over finish line? :)

**Comment by Dharmik79** [comment]
@konopkja I have fixed the changes requested by @wackerow, and waiting for the review and merge.

File: src/components/FindWallet/WalletTable/index.tsx [hunk 3]
```diff
@@ -310,6 +310,8 @@ const WalletTable = ({
           )
 
           const showMoreInfo = (wallet) => {
+            // Prevent expanding the wallet more info section when clicking on the "Visit website" button
+
```
Comment (wackerow) [inline src/components/FindWallet/WalletTable/index.tsx:314]: Last thing, just going to move this comment next to the onClick handler where it's referencing

```suggestion
```

File: src/components/FindWallet/WalletTable/index.tsx [hunk 4]
```diff
@@ -330,7 +332,13 @@ const WalletTable = ({
                 onKeyUp={(e) => {
                   if (e.key === "Enter") showMoreInfo(wallet)
                 }}
-                onClick={() => showMoreInfo(wallet)}
+                onClick={(e) => {
+                  if (
```
Comment (wackerow) [inline src/components/FindWallet/WalletTable/index.tsx:336]:
```suggestion
                  // Prevent expanding the wallet more info section when clicking on the "Visit website" button
                  if (
```

**Review by wackerow — APPROVED** [review]
Looks good! Thanks @Dharmik79

**Comment by wackerow** [comment]
@all-contributors please add @Dharmik79 for bug fix
