### PR TITLE
hot-fix: update page edit path logic [Fixes #11994]

### LINKED ISSUE #11994: "Edit page" link on TOC is broken
### Describe the bug

The "Edit page" button link on the top of the TOC is broken.

Currently, it will redirect to e.g.:
https://ethereum.org/github.com/ethereum/ethereum-org-website/tree/dev/public/content/developers/docs/index.md

But it should be:
https://github.com/ethereum/ethereum-org-website/tree/dev/public/content/developers/docs/index.md

instead.

It seems to be the link href is parsed as a relative path, but we should treat it as an absolute path.

### To reproduce

1. Go to somewhere in the "Developers => Docs" page
2. Click on the "Edit page" button

### Expected behavior

It should be redirected to Github, instead of ethereum.org.

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by wackerow**
## Description
Updates construction of the "edit path" url to use `new URL()` when adding the base path. Current production uses `join` which collapses the repeated slashes in `https://` and causes broken paths. 

## Related Issue
- Fixes #11994

### CODE REVIEW

**Review by corwintines — DISMISSED** [review]

File: src/lib/utils/editPath.ts [hunk 1]
```diff
@@ -2,4 +2,7 @@ import { join } from 'path'
 
 import { CONTENT_DIR, EDIT_CONTENT_URL } from '@/lib/constants'
 
-export const getEditPath = (relativePath: string): string => join(EDIT_CONTENT_URL, CONTENT_DIR, relativePath, "index.md")
+export const getEditPath = (relativePath: string): string => {
+  const { href } = new URL(join(CONTENT_DIR, relativePath, "index.md"), EDIT_CONTENT_URL)
+  return href
```
Comment (nhsz) [inline src/lib/utils/editPath.ts:7]:
```suggestion
```

File: src/lib/utils/editPath.ts [hunk 2]
```diff
@@ -2,4 +2,7 @@ import { join } from 'path'
 
 import { CONTENT_DIR, EDIT_CONTENT_URL } from '@/lib/constants'
 
-export const getEditPath = (relativePath: string): string => join(EDIT_CONTENT_URL, CONTENT_DIR, relativePath, "index.md")
+export const getEditPath = (relativePath: string): string => {
+  const { href } = new URL(join(CONTENT_DIR, relativePath, "index.md"), EDIT_CONTENT_URL)
```
Comment (nhsz) [inline src/lib/utils/editPath.ts:6]:
```suggestion
return new URL(join(CONTENT_DIR, relativePath, "index.md"), EDIT_CONTENT_URL)
```

**Review by nhsz — CHANGES_REQUESTED** [review]
Thanks for the fix, small suggestion on the return value

File: src/lib/utils/editPath.ts (hunk 2 above)
Comment (wackerow) [reply src/lib/utils/editPath.ts:6]: @nhsz This will give us the entire URL object... wouldn't we want to just return the path here?

image

Comment (nhsz) [reply src/lib/utils/editPath.ts:6]: missing the `.href` at the end

Comment (wackerow) [reply src/lib/utils/editPath.ts:6]: Oh okay... fairly indifferent myself, added for readability but can switch it over

**Review by nhsz — APPROVED** [review]
LGTM!

**Review by corwintines — APPROVED** [review]
