### PR TITLE
Deploy v2.7.13

### LINKED ISSUE #1647: Site Translation: Update Brazilian Portuguese to v1.1
### Challenge Description
Brazilian Portuguese translations have completed review & are ready to be added to the website!

### Submission Requirements
1. Download the [files from CrowdIn](https://crowdin.com/project/ethereumfoundation/pt-BR#) for this version of the content (`Contents v.1.1`) - here's a [screenshot showing how](https://share.getcloudapp.com/ApujZjyn). You may need to sign up for Crowdin & join our project in order to download the files - here's the [invite link](https://crowdin.com/project/ethereumfoundation/invite).

2. Copy in the v1.1 Crowdin files:
- Replace all files within the /src/content/translations/pt-br/ directory & add any new files, keeping the same directory structure as CrowdIn (i.e. each page is a subdirectory with an index.md filename, a strings.json & an index.md at the root of the directory)
- Copy the strings.json file into the /src/intl/ directory & rename it to pt-br.json (i.e. /src/intl/pt-br.json), replacing the existing file
- Delete the root index.md file (i.e. /src/content/translations/pt-br/index.md)
	- Beforehand: within the index.md file, move the `title` value & `og:description`'s `content` property into the pt-br.json file from the previous step. Use the keys `"page-home-meta-title"` & `"page-home-meta-description"` as keys for these values. (See [en.json](https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en.json#L95) as an example for how this should look)
- Delete the /build/ directory (i.e. /src/content/translations/pt-br/build/)
	- Beforehand: within the index.md file of /build/, move the `title` value & `og:description`'s `content` property into the pt-br.json file from the previous step. Use the keys `"page-build-meta-title"` & `"page-build-meta-description"` as keys for these values. (See [en.json](https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en.json#L53) as an example for how this should look)

3. Within each newly added markdown file...
- Ensure each file is valid markdown (sometimes Crowdin throws in some wacky HTML elements, like a `<br>` or a `<em>`, that breaks the site build)
- Update the frontmatter:
    - Update the `lang` property (it should be `it`)
    - Remove any `og:title` or `og:description` properties - replace those contents with `title` & `description` field names
    - Update all `sidebar` fields from `auto` to `true`
    - Increase all `sidebarDepth` fields by 1 (e.g. 0 --> 1 & 1 --> 2)
    - (It might help to [use this commit as a reference](https://github.com/ethereum/ethereum-org-website/pull/1221/commits/bc1f62929147eb32df981a9d1a784f04636f2775))

4. Update the `pt-br` object in [the languageMetadata object within /src/utils/translations.js](https://github.com/ethereum/ethereum-org-website/blob/dev/src/utils/translations.js#L5) from `version: 1.0` to `version: 1.1`

### Additional context

See this recent PR as a guide: https://github.com/ethereum/ethereum-org-website/pull/1455

### LINKED ISSUE #1661: Morpher component not cycling back to start after last word
**Describe the bug 🐞**
Currently `Morpher.js` component will iterate through an array of words to "morph" through, but upon reaching the last word the counter does not properly reset and the last word in the list persists.

**To Reproduce**

1. Go to 'www.ethereum.org' on desktop-sized screen
2. Slightly shift your gaze just below the home banner on the right side
3. Wait patiently for it to cycle through all 18 translations available
4. Gets stuck on last word

**Expected behavior**
Expect each name be displayed once at a time, in order, then cycle back to the first item after the last.

**Screenshots**
image
..Just to make it clear which component we're talking about, but it's more of a dynamic thing (I'll spare the video or looping gif)

**Desktop 🖥:**
- OS: macOS Big Sur
- Browser: Brave
- Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (x86_64)

**Smartphone 📱:**
- Device: iPad Pro
- OS: iPad OS 14
- Browser: Brave

**Additional context**
Will take a look at this myself.

_(While I'm looking at this, any thoughts on making this component a link to `/languages/`?)_

### LINKED ISSUE #1667: Warning: React does not recognize the `marginLeft` prop on a DOM element
**Describe the bug**
```
index.js:2177 Warning: React does not recognize the `marginLeft` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `marginleft` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in span (created by Emoji)
    in Emoji (created by Twemoji)
    in Twemoji (created by Emoji__StyledEmoji)
    in Emoji__StyledEmoji (at Emoji.js:14)
    in Emoji (at Mobile.js:317)
    in div (created by Mobile__BlankSearchState)
    in Mobile__BlankSearchState (at Mobile.js:316)
    in div (created by ForwardRef(MotionComponent))
    ...
```

Getting this error since Twemoji implemented. There are four console errors, one for each `prop` being passed to `<StyledEmoji />` component (`marginLeft`, `marginTop`, `marginRight`, `marginBottom`), and it essentially tells you how to fix it in the error.

**To Reproduce**

1. Run project locally
2. Go to http://localhost:8888/en/
3. View console error

**Expected behavior**
Properly display Twemojis without console errors, passing margin props appropriately.

**Desktop:**
- OS: macOS Big Sur
- Browser: Brave (Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (x86_64))

**Smartphone:** _not tested_

**Additional context**
Looks pretty straight forward... will put into PR fixing prop names

### LINKED ISSUE #1677: Mobile UI header bug on developer docs pages
**Describe the bug**
A small gap exists between the top _header bar_ on mobile devices, and the _title banner_ on the developer documentation pages. 

**To Reproduce**

0. Using a screen/window size less than 1024px wide...
1. Go to 'https://ethereum.org/en/developers/docs/'
2. On any page in this section, as you scroll down you'll notice contents appearing above the title banner and below the header through a small gap.

**Expected behavior**
Readers of development documentation shouldn't see @samajammin peering through 😜 

**Screenshots**
image
image

**Desktop:**
- OS: macOS Big Sur
- Browser: Brave latest (windows <1024px wide)

**Smartphone:**
- Device: iPhone XS Max
- OS: iOS14
- Browser: Brave latest

**Additional context**
Can take a look at this if you want to assign me.

### LINKED ISSUE #1692: Site Translation: Update Spanish to v1.1
### Challenge Description
Spanish translations have completed review & are ready to be added to the website!

### Submission Requirements
1. Download the [files from CrowdIn](https://crowdin.com/project/ethereumfoundation/es-EM#) for this version of the content (`Contents v.1.1`) - here's a [screenshot showing how](https://share.getcloudapp.com/ApujZjyn). You may need to sign up for Crowdin & join our project in order to download the files - here's the [invite link](https://crowdin.com/project/ethereumfoundation/invite).

2. Copy in the v1.1 Crowdin files:
- Replace all files within the /src/content/translations/es/ directory & add any new files, keeping the same directory structure as CrowdIn (i.e. each page is a subdirectory with an index.md filename, a strings.json & an index.md at the root of the directory)
- Copy the strings.json file into the /src/intl/ directory & rename it to es.json (i.e. /src/intl/es.json), replacing the existing file
- Delete the root index.md file (i.e. /src/content/translations/es/index.md)
	- Beforehand: within the index.md file, move the `title` value & `og:description`'s `content` property into the es.json file from the previous step. Use the keys `"page-home-meta-title"` & `"page-home-meta-description"` as keys for these values. (See [en.json](https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en.json#L95) as an example for how this should look)
- Delete the /build/ directory (i.e. /src/content/translations/es/build/)
	- Beforehand: within the index.md file of /build/, move the `title` value & `og:description`'s `content` property into the es.json file from the previous step. Use the keys `"page-build-meta-title"` & `"page-build-meta-description"` as keys for these values. (See [en.json](https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en.json#L53) as an example for how this should look)

3. Within each newly added markdown file...
- Ensure each file is valid markdown (sometimes Crowdin throws in some wacky HTML elements, like a `<br>` or a `<em>`, that breaks the site build)
- Update the frontmatter:
    - Update the `lang` property (it should be `it`)
    - Remove any `og:title` or `og:description` properties - replace those contents with `title` & `description` field names
    - Update all `sidebar` fields from `auto` to `true`
    - Increase all `sidebarDepth` fields by 1 (e.g. 0 --> 1 & 1 --> 2)
    - (It might help to [use this commit as a reference](https://github.com/ethereum/ethereum-org-website/pull/1221/commits/bc1f62929147eb32df981a9d1a784f04636f2775))

4. Update the `es` object in [the languageMetadata object within /src/utils/translations.js](https://github.com/ethereum/ethereum-org-website/blob/dev/src/utils/translations.js#L5) from `version: 1.0` to `version: 1.1`

### Additional context

See this recent PR as a guide: https://github.com/ethereum/ethereum-org-website/pull/1455

### PR DESCRIPTION
**Pull request by samajammin**
***
### :zap: Changes
- Adds "Previous" & "Next" links to Developer Docs pages [Addresses #1650] (#1670) @wackerow
- Fix GWEI <-> ETH Unit Conversion (#1678) @joncursi
- Added Link to DAppNode to Nodes doc (#1681) @joncursi
- Adjusts mobile docs navbar and content position [Fixes #1677] (#1682) @wackerow
- Fix Epirus description (#1688) @xaviarias
- Fix broken link to 'Understand the ERC20 token smart contract' (#1675) @jamespfarrell
- Add missing comma (#1679) @joncursi
- Added Link to Etherscan Gas Tracker (#1680) @joncursi
- Morpher component properly cycles, now links to /en/languages/ [Fixes #1661] (#1666) @wackerow
- Adjusted StyledEmoji margin prop names to lowercase [Fixes #1667] (#1668) @wackerow

## :globe_with_meridians: Translations

- translated es to v1.1. [Fixes #1692] (#1693) @ph5500
- updated pt-br translations to v1.1. [Fixes #1647] (#1653) @ph5500

## :wrench: Tooling

- Update docsearch languages to index (#1690) @samajammin
- updated pt-br translations to v1.1. [Fixes #1647] (#1653) @ph5500

***
### :unicorn: Contributors
Thank you @jamespfarrell, @joncursi, @ph5500, @ryancreatescopy, @samajammin, @wackerow and @xaviarias for the contributions! :trophy:
***

### CODE REVIEW

File: src/data/addresses.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+// TODO update once deployed
```
Comment (samajammin) [inline src/data/addresses.js:1]: FYI @jjmstark @ryancreatescopy - this is the file to keep an eye on.

**Review by jjmstark — APPROVED** [review]

**Review by ryancreatescopy — APPROVED** [review]
