### PR TITLE
NavItems visibility@1000px fixed.

### LINKED ISSUE #9606: Navbar items are not visible
### Describe the bug

Navbar items are not visible for a small range of screen widths (`995px` - `1020px`).

### To reproduce

1. Go to [ethereum website](https://ethereum.org/en/)
2. Change the screen width to `1000px`
3. See error

### Expected behavior

**Navbar items should be visible**

### Screenshots

image

### Desktop (please complete the following information)

- OS: Windows 10
- Browser: Brave

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rohitt-gupta**
## Related Issue
fixes #9606

### CODE REVIEW

File: src/components/Nav/index.tsx [hunk 1]
```diff
@@ -59,9 +59,6 @@ const InnerContent = styled.div`
   display: flex;
   justify-content: space-between;
   width: 100%;
-  @media (max-width: ${(props) => props.theme.breakpoints.l}) {
-    display: none;
-  }
```
Comment (TylerAPfledderer) [inline src/components/Nav/index.tsx:64]: Unfortunately, simply removing this will break the layout at smaller screens.
Screen Shot 2023-03-04 at 13 23 18

A solution to apply for now would be to wrap `InnerContent` with the Chakra `Show` component in the render (line 395) and use the `useToken` hook to extract the correct breakpoint value.

So above the render return 
```tsx
// Make sure `useToken` is imported from Chakra
const lgBreakpoint = useToken("breakpoints", "lg")
```

And in the return at line 395

```tsx
<Show above={lgBreakpoint} >
  <InnerContent>{/*  */}</InnerContent>
</Show>
```

For @pettinarip, since I am handling migration of the entire `Nav`, I guess up to you on if you want to get this fix in now, since I am waiting on a couple of other PRs as well that involve the `Nav`

**Review by TylerAPfledderer — CHANGES_REQUESTED** [review]
Hey @rohitt-gupta! Left some feedback here. 😄

File: src/components/Nav/index.tsx (hunk 1 above)
Comment (rohitt-gupta) [reply src/components/Nav/index.tsx:64]: @TylerAPfledderer this is what i have been waiting for, "The Feedback". 
thankyou, I will apply these changes.

Comment (corwintines) [reply src/components/Nav/index.tsx:64]: @TylerAPfledderer @pettinarip @rohitt-gupta I found a simpler way to do this just using Flex for now. I know we are planning on migrating this fully in the future, but for the purposes of this PR I think its a bit cleaner and achieves the same thing. Going to merge with that for now.

**Review by corwintines — APPROVED** [review]
Thanks @rohitt-gupta!

I found a bit of a simpler way to achieve this, feel free to see what I did. Going to merge this for now :)

File: src/components/Nav/index.tsx (hunk 1 above)
Comment (pettinarip) [reply src/components/Nav/index.tsx:64]: Cool, thanks for the feedback @TylerAPfledderer.

Thanks @rohitt-gupta for the PR and agreed @corwintines, lets have this as a patch for now.
