### PR TITLE
Switches tx count to etherscan API [Fixes #2362]

### LINKED ISSUE #2362: Coin Metrics API endpoint fails
**Describe the bug**

Requests to Coin Metrics API is timing out:
Image 2021-02-01 at 6 06 47 PM

Even tried requesting from browser:
https://community-api.coinmetrics.io/v2/assets/eth/metricdata/?metrics=TxCnt

Image 2021-02-01 at 6 09 43 PM

**To Reproduce**

1. Go to ethereum.org homepage
2. See error

**Expected behavior**

Should work 😕 

**Screenshots**

See above

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All
**Additional context**

Etherscan has a "Get Daily Transaction Count" endpoint that should solve this:
https://api.etherscan.io/api?module=stats&action=dailytx&startdate=2019-02-01&enddate=2019-02-28&sort=asc&apikey=YourApiKeyToken

Perhaps we go with that since they were kind enough to provide a Pro API key.

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Added new lambda function for call to Etherscan API to pull transaction counts
- Created second lambda for Etherscan in the event one endpoint fails, this will not block the other from potentially displaying
- Pulling 30-days of data in anticipation of charting, but currently only displaying current

## Related Issue 
#2362

### CODE REVIEW

**Review by ryancreatescopy — APPROVED** [review]

File: src/lambda/txs.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
+const axios = require("axios")
+
+const handler = async () => {
+  try {
+    const dayToFetch = 30
```
Comment (samajammin) [inline src/lambda/txs.js:5]:
```suggestion
    const daysToFetch = 30
```

File: src/lambda/txs.js [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+    const milliseconds = dayToFetch * 24 * 60 * 60 * 1000
```
Comment (samajammin) [inline src/lambda/txs.js:6]:
```suggestion
    const milliseconds = daysToFetch * 24 * 60 * 60 * 1000
```

**Review by samajammin — APPROVED** [review]
