### PR TITLE
fix table out of size issue

### LINKED ISSUE #8320: Table out of size
### Describe the bug

The table on this page is way out of the grid

https://ethereum.org/en/developers/docs/evm/opcodes/

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/evm/opcodes/
2. See the page content

### Expected behavior

The table should be within the page grid with overflow scroll

### Screenshots

Screen Shot 2022-10-21 03 01 09 PM

### Desktop (please complete the following information)

Mac OS

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Aksa12**
Fixed table overflowing on https://ethereum.org/en/developers/docs/evm/opcodes/ page. 

Fixes #8320

Screenshot 2022-10-23 at 10 40 55 PM

### CODE REVIEW

File: src/components/MarkdownTable.tsx [hunk 1]
```diff
@@ -6,7 +6,12 @@ export interface IProps {
 }
 
 const MarkdownTable: React.FC<IProps> = ({ children }) => (
-  <Box my={8}>
+  <Box
+    my={8}
+    sx={{
```
Comment (corwintines) [inline src/components/MarkdownTable.tsx:11]: We actually don't need the sx prop here: https://chakra-ui.com/docs/styled-system/the-sx-prop
```
sx={{
    overflowX: "auto",
  }}
```

We can just use `overflowX` as a prop style instead here. Ill push that up.

**Review by corwintines — APPROVED** [review]
