### PR TITLE
Fix: component padding on /stablecoins

### LINKED ISSUE #12649: UI Bug report: missing padding on stablecoins page
### Describe the bug

there is missing padding between the box and the text below it. 

### To reproduce

1. Go to https://ethereum.org/en/stablecoins/
2. Scroll down to "Top stablecoins by market capitalisation" section
4. See error: warning message missing padding from text bellow it.

Screenshot 2024-04-03 at 12 48 03

### Expected behavior

Add padding between the warning message and the text:

 "Market capitalisation is the total number of tokens that exist multiplied by the value per token. This list is dynamic and the projects listed here are not necessarily endorsed by the ethereum.org team."

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by Dharmik79**
## Description
Added the padding between the warning and the text [Fixes #12649 ]

## Preview link
https://deploy-preview-12659--ethereumorg.netlify.app/en/stablecoins

## Related issue
- Fixes #12649

### CODE REVIEW

File: src/pages/stablecoins.tsx [hunk 1]
```diff
@@ -614,7 +614,7 @@ const StablecoinsPage = ({ markets, marketsHasError }) => {
           <InfoBanner emoji="⚠️" isWarning>
```
Comment (wackerow) [inline src/pages/stablecoins.tsx:614]: I would suggest we place this on the InfoBanner as a margin bottom instead:

```suggestion
          <InfoBanner emoji="⚠️" isWarning pb="4">
```

Also @konopkja, does 1rem look like enough here for you? The padding in the info banner and the margin between it and the header is 1.5rem for reference

File: src/pages/stablecoins.tsx [hunk 2]
```diff
@@ -614,7 +614,7 @@ const StablecoinsPage = ({ markets, marketsHasError }) => {
...
             {t("page-stablecoins-algorithmic-disclaimer")}
           </InfoBanner>
-          <Text>
+          <Text py={4}>
```
Comment (wackerow) [inline src/pages/stablecoins.tsx:617]:
```suggestion
          <Text>
```

**Review by wackerow — CHANGES_REQUESTED** [review]
Thanks @Dharmik79! Left a request and a question

**Comment by wackerow** [comment]
@all-contribuitors please add @Dharmik79 for bug fix

**Comment by wackerow** [comment]
@all-contributors please add @Dharmik79 for bug fix
