### PR TITLE
Fix Nav styles to match DS header

### LINKED ISSUE #10807: Incorrect font size in color mode and language buttons
### Describe the bug

The current font size for the color mode and language buttons is too small.

### To reproduce

1. Go to the home page
2. See error on the color mode & language buttons on the nav bar

### Expected behavior

Font size should be the `md` size (1rem or 16px).

### Screenshots

image

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by pettinarip**
## Description

This PR fixes the styles issues reported in #10807 but also refactor the `Nav` component to match the DS.

## TODO
- [x] replace & remove deprecated `icon` variant
- [x] update docs if necessary
- [x] @TylerAPfledderer see if we can still use the previous api for the Button theme (using `isSecondary`) and refactor accordingly

## Related Issue

#9546 
Fixes #10807

### CODE REVIEW

File: src/components/Nav/index.tsx [hunk 1]
```diff
@@ -62,52 +63,48 @@ const Nav: FC<IProps> = ({ path }) => {
...
-              </ButtonLink>
+              <HStack spacing={2} hideBelow="lg">
+                <Button
+                  aria-label={
+                    isDarkTheme
+                      ? "Switch to Light Theme"
+                      : "Switch to Dark Theme"
+                  }
+                  variant="secondaryGhost"
+                  px={1.5}
```
Comment (pettinarip) [inline src/components/Nav/index.tsx:92]: I'd like to have your 👀 on this PR @TylerAPfledderer, especially with the following changes:

1st change is in the `Button` component, where I had to remove the `sx` inner logic because otherwise, I wasn't able to override the `px` prop. Not sure exactly why (I think it is because the `sx` prop has more priority than the style props).

2nd change is a consequence of the 1st one. Since I removed the usage of `useStyleConfig` and `sx` from the Button component (and ButtonLink), I started to see the warning about the `isSecondary` flag. I ended up removing it and creating 2 new variants to cover the secondary cases. Not ideal I think, but it worked and is simple to understand.

Let me know what do you think about these changes or if you have any concerns. Also, feel free to test the rest of the changes as well and leave any comments :)

File: src/components/Nav/index.tsx [hunk 2]
```diff
@@ -62,52 +63,48 @@ const Nav: FC<IProps> = ({ path }) => {
...
-              gap={{ base: 1, xl: 0 }}
+              gap={{ base: 2, xl: 4 }}
             >
-              <Search ref={searchRef} />
-              <IconButton
-                aria-label={
-                  isDarkTheme ? "Switch to Light Theme" : "Switch to Dark Theme"
-                }
-                icon={<Icon as={isDarkTheme ? MdWbSunny : MdBrightness2} />}
-                variant="icon"
```
Comment (pettinarip) [inline src/components/Nav/index.tsx:82]: Trying to remove as much as I can the `icon` variant to finally delete it from the theme.

File: src/components/Nav/index.tsx [hunk 3]
```diff
@@ -25,9 +26,9 @@ const Nav: FC<IProps> = ({ path }) => {
     t,
     toggleColorMode,
     linkSections,
-    searchRef,
     mobileNavProps,
   } = useNav({ path })
+  const searchModalDisclosure = useDisclosure()
```
Comment (pettinarip) [inline src/components/Nav/index.tsx:31]: Moved the search modal logic to the parent to avoid using refs which was causing me a headache.

File: src/components/Search/index.tsx [hunk 4]
```diff
@@ -27,142 +27,145 @@ import { trackCustomEvent } from "../../utils/matomo"
...
-    />
+    <Button ref={ref} variant="secondaryGhost" px={1.5} {...props}>
+      <MdSearch />
+    </Button>
   )
 )
 
-const Search = forwardRef<{}, "button">((_, ref) => {
-  const searchButtonRef = React.useRef<HTMLButtonElement>(null)
-  const { isOpen, onClose, onOpen } = useDisclosure()
```
Comment (pettinarip) [inline src/components/Search/index.tsx:43]: Main change here was the removal of this line. It was moved to the parent component (the Nav).

File: src/components/Nav/index.tsx (hunk 1 above)
Comment (TylerAPfledderer) [reply src/components/Nav/index.tsx:92]: To the first, I can see where the issue would happen, so this is definitely cleaner! 😄 

As to the second, it is certainly a matter of preference. I guess here it is readability versus overkill? I'm good with this though! Indeed still easy to roll with.

File: src/components/Nav/index.tsx (hunk 3 above)
Comment (TylerAPfledderer) [reply src/components/Nav/index.tsx:31]: Good call here 😅

File: src/components/Nav/index.tsx [hunk 5]
```diff
@@ -62,52 +63,48 @@ const Nav: FC<IProps> = ({ path }) => {
...
+                    isDarkTheme
+                      ? "Switch to Light Theme"
+                      : "Switch to Dark Theme"
+                  }
+                  variant="secondaryGhost"
+                  px={1.5}
+                  onClick={toggleColorMode}
+                >
+                  <Icon as={isDarkTheme ? MdWbSunny : MdBrightness2} />
+                </Button>
```
Comment (TylerAPfledderer) [inline src/components/Nav/index.tsx:96]: Using `IconButton` also works here, and still simplified from the original
```suggestion
                <IconButton
                  icon={isDarkTheme ? <MdWbSunny /> : <MdBrightness2 />}
                  aria-label={
                    isDarkTheme
                      ? "Switch to Light Theme"
                      : "Switch to Dark Theme"
                  }
                  variant="secondaryGhost"
                  px={1.5}
                  onClick={toggleColorMode}
                />
```

**Review by TylerAPfledderer — CHANGES_REQUESTED** [review]
Only one additional thought I had here. 😄

File: src/components/Nav/index.tsx (hunk 1 above)
Comment (pettinarip) [reply src/components/Nav/index.tsx:92]: Thanks @TylerAPfledderer 

This PR is a draft because I wanted to first check with you about it and see if you had a workaround to keep the same convention you built (with simpler variants + the `isSecondary` flag). Tbh I don't like having variants called `"secondaryOutline"` hahaha.

So, let me know if you prefer to hold on a bit here and see if you can add the necessary changes to make this work with the original convention you did.

Comment (pettinarip) [reply src/components/Nav/index.tsx:92]: Awesome thanks!

LMK if you can add commits to this PR (I doubt it) or create a new PR off this branch and we can merge it back.

File: src/components/Nav/index.tsx (hunk 5 above)
Comment (TylerAPfledderer) [reply src/components/Nav/index.tsx:96]: I'm not sure why it would be doing that. I'm not seeing that issue when I try to apply it. Maybe something to follow up with later once this PR gets pushed?

Comment (pettinarip) [reply src/components/Nav/index.tsx:96]: Hmm probably I was just doing silly things and it works fine xD

Yea...lets leave it for now and we can tackle it later.

**Review by corwintines — APPROVED** [review]
Nice!
